# Generated by Django 5.1.4 on 2024-12-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airplane",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("amount_of_passengers", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
